# Generated by Django 5.2.2 on 2025-06-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etlprocessinglog",
            name="batches_posted",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
